/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Wed May 05 11:29:43 GMT+05:30 2010
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.scrum.pojo;

import java.util.Set;

/*
 * For Table products
 */
public class Products implements java.io.Serializable, Cloneable {

    /* Product_ID, PK */
    protected int productId;

    /* Product_Code */
    protected String productCode;

    /* Product_Name */
    protected String productName;

    /* Domain_FK */
    protected int domainFk;
    protected Set<Themes> themeSet;
    protected Set<Versions> versionSet;

    /* Product_Status_FK */
    protected int productStatusFk;

    /* Product_Comment */
    protected byte[] productComment;

    /* Product_date_start */
    protected java.util.Date productDateStart;

    /* Product_date_end */
    protected java.util.Date productDateEnd;

    /* Product_taskTypes */
    protected byte[] productTasktypes;

    /* Product_Roles */
    protected byte[] productRoles;

    /* Product_ID, PK */
    public int getProductId() {
        return productId;
    }

    /* Product_ID, PK */
    public void setProductId(int productId) {
        this.productId = productId;
    }

    /* Product_Code */
    public String getProductCode() {
        return productCode;
    }

    /* Product_Code */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /* Product_Name */
    public String getProductName() {
        return productName;
    }

    /* Product_Name */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /* Domain_FK */
    public int getDomainFk() {
        return domainFk;
    }

    /* Domain_FK */
    public void setDomainFk(int domainFk) {
        this.domainFk = domainFk;
    }

    /* Product_Status_FK */
    public int getProductStatusFk() {
        return productStatusFk;
    }

    /* Product_Status_FK */
    public void setProductStatusFk(int productStatusFk) {
        this.productStatusFk = productStatusFk;
    }

    /* Product_Comment */
    public byte[] getProductComment() {
        return productComment;
    }

    /* Product_Comment */
    public void setProductComment(byte[] productComment) {
        this.productComment = productComment;
    }

    /* Product_date_start */
    public java.util.Date getProductDateStart() {
        return productDateStart;
    }

    /* Product_date_start */
    public void setProductDateStart(java.util.Date productDateStart) {
        this.productDateStart = productDateStart;
    }

    /* Product_date_end */
    public java.util.Date getProductDateEnd() {
        return productDateEnd;
    }

    /* Product_date_end */
    public void setProductDateEnd(java.util.Date productDateEnd) {
        this.productDateEnd = productDateEnd;
    }

    /* Product_taskTypes */
    public byte[] getProductTasktypes() {
        return productTasktypes;
    }

    /* Product_taskTypes */
    public void setProductTasktypes(byte[] productTasktypes) {
        this.productTasktypes = productTasktypes;
    }

    /* Product_Roles */
    public byte[] getProductRoles() {
        return productRoles;
    }

    /* Product_Roles */
    public void setProductRoles(byte[] productRoles) {
        this.productRoles = productRoles;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Products))
            return false;

        Products bean = (Products) obj;

        if (this.productId != bean.productId)
            return false;

        if (this.productCode == null) {
            if (bean.productCode != null)
                return false;
        }
        else if (!this.productCode.equals(bean.productCode)) 
            return false;

        if (this.productName == null) {
            if (bean.productName != null)
                return false;
        }
        else if (!this.productName.equals(bean.productName)) 
            return false;

        if (this.domainFk != bean.domainFk)
            return false;

        if (this.productStatusFk != bean.productStatusFk)
            return false;

        if (this.productComment == null) {
            if (bean.productComment != null)
                return false;
        }else {
            if (bean.productComment == null)
                return false;
            else {
                if (productComment.length != bean.productComment.length)
                    return false;
                for (int i=0;i<bean.productComment.length;i++) {
                    if (this.productComment[i] != bean.productComment[i])
                        return false;
                }
            }
        }

        if (this.productDateStart == null) {
            if (bean.productDateStart != null)
                return false;
        }
        else if (!this.productDateStart.equals(bean.productDateStart)) 
            return false;

        if (this.productDateEnd == null) {
            if (bean.productDateEnd != null)
                return false;
        }
        else if (!this.productDateEnd.equals(bean.productDateEnd)) 
            return false;

        if (this.productTasktypes == null) {
            if (bean.productTasktypes != null)
                return false;
        }else {
            if (bean.productTasktypes == null)
                return false;
            else {
                if (productTasktypes.length != bean.productTasktypes.length)
                    return false;
                for (int i=0;i<bean.productTasktypes.length;i++) {
                    if (this.productTasktypes[i] != bean.productTasktypes[i])
                        return false;
                }
            }
        }

        if (this.productRoles == null) {
            if (bean.productRoles != null)
                return false;
        }else {
            if (bean.productRoles == null)
                return false;
            else {
                if (productRoles.length != bean.productRoles.length)
                    return false;
                for (int i=0;i<bean.productRoles.length;i++) {
                    if (this.productRoles[i] != bean.productRoles[i])
                        return false;
                }
            }
        }

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Products bean = new Products();
        bean.productId = this.productId;
        bean.productCode = this.productCode;
        bean.productName = this.productName;
        bean.domainFk = this.domainFk;
        bean.productStatusFk = this.productStatusFk;
        int productCommentLength = -1;
        if (this.productComment != null)
            productCommentLength = this.productComment.length;
        if (productCommentLength > 0)
        {
            byte[] productCommentArray = new byte[productCommentLength];
            bean.productComment = productCommentArray;
            System.arraycopy(this.productComment, 0, productCommentArray, 0, productCommentLength);
        }
        if (this.productDateStart != null)
            bean.productDateStart = (java.util.Date) this.productDateStart.clone();
        if (this.productDateEnd != null)
            bean.productDateEnd = (java.util.Date) this.productDateEnd.clone();
        int productTasktypesLength = -1;
        if (this.productTasktypes != null)
            productTasktypesLength = this.productTasktypes.length;
        if (productTasktypesLength > 0)
        {
            byte[] productTasktypesArray = new byte[productTasktypesLength];
            bean.productTasktypes = productTasktypesArray;
            System.arraycopy(this.productTasktypes, 0, productTasktypesArray, 0, productTasktypesLength);
        }
        int productRolesLength = -1;
        if (this.productRoles != null)
            productRolesLength = this.productRoles.length;
        if (productRolesLength > 0)
        {
            byte[] productRolesArray = new byte[productRolesLength];
            bean.productRoles = productRolesArray;
            System.arraycopy(this.productRoles, 0, productRolesArray, 0, productRolesLength);
        }
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("productId").append(" = ").append(productId).append("]").append(sep);
        sb.append("[").append("productCode").append(" = ").append(productCode).append("]").append(sep);
        sb.append("[").append("productName").append(" = ").append(productName).append("]").append(sep);
        sb.append("[").append("domainFk").append(" = ").append(domainFk).append("]").append(sep);
        sb.append("[").append("productStatusFk").append(" = ").append(productStatusFk).append("]").append(sep);
        sb.append("[").append("productComment").append(" = ").append(productComment).append("]").append(sep);
        sb.append("[").append("productDateStart").append(" = ").append(productDateStart).append("]").append(sep);
        sb.append("[").append("productDateEnd").append(" = ").append(productDateEnd).append("]").append(sep);
        sb.append("[").append("productTasktypes").append(" = ").append(productTasktypes).append("]").append(sep);
        sb.append("[").append("productRoles").append(" = ").append(productRoles).append("]").append(sep);
        return sb.toString();
    }

	public Set<Themes> getThemeSet() {
		return themeSet;
	}

	public void setThemeSet(Set<Themes> themeSet) {
		this.themeSet = themeSet;
	}

	public Set<Versions> getVersionSet() {
		return versionSet;
	}

	public void setVersionSet(Set<Versions> versionSet) {
		this.versionSet = versionSet;
	}
}