/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Wed May 05 11:29:43 GMT+05:30 2010
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.scrum.pojo;

/*
 * For Table profiles
 */
public class Profiles implements java.io.Serializable, Cloneable {

    /* Profile_ID, PK */
    protected int profileId;

    /* Profile_label */
    protected String profileLabel;

    /* profile_code */
    protected String profileCode;
 

    /* Profile_ID, PK */
    public int getProfileId() {
        return profileId;
    }

    /* Profile_ID, PK */
    public void setProfileId(int profileId) {
        this.profileId = profileId;
    }

    /* Profile_label */
    public String getProfileLabel() {
        return profileLabel;
    }

    /* Profile_label */
    public void setProfileLabel(String profileLabel) {
        this.profileLabel = profileLabel;
    }

    /* profile_code */
    public String getProfileCode() {
        return profileCode;
    }

    /* profile_code */
    public void setProfileCode(String profileCode) {
        this.profileCode = profileCode;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Profiles))
            return false;

        Profiles bean = (Profiles) obj;

        if (this.profileId != bean.profileId)
            return false;

        if (this.profileLabel == null) {
            if (bean.profileLabel != null)
                return false;
        }
        else if (!this.profileLabel.equals(bean.profileLabel)) 
            return false;

        if (this.profileCode == null) {
            if (bean.profileCode != null)
                return false;
        }
        else if (!this.profileCode.equals(bean.profileCode)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Profiles bean = new Profiles();
        bean.profileId = this.profileId;
        bean.profileLabel = this.profileLabel;
        bean.profileCode = this.profileCode;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("profileId").append(" = ").append(profileId).append("]").append(sep);
        sb.append("[").append("profileLabel").append(" = ").append(profileLabel).append("]").append(sep);
        sb.append("[").append("profileCode").append(" = ").append(profileCode).append("]").append(sep);
        return sb.toString();
    }
}