/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Wed May 05 11:29:43 GMT+05:30 2010
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.scrum.pojo;

import java.util.Set;

/*
 * For Table reports
 */
public class Reports implements java.io.Serializable, Cloneable {

    /* Report_ID, PK */
    protected int reportId;

    /* Report_Name */
    protected String reportName;
    
    protected Set<Columns> columnSet;
    /* BarCol_FK */
    protected int barcolFk;

    /* SeriesCol_FK */
    protected int seriescolFk;

    /* BarChart_Name */
    protected String barchartName;

    /* PieChart_Name */
    protected String piechartName;

    /* Profile_FK */
    protected int profileFk; 
 

    /* Report_ID, PK */
    public int getReportId() {
        return reportId;
    }

    /* Report_ID, PK */
    public void setReportId(int reportId) {
        this.reportId = reportId;
    }

    /* Report_Name */
    public String getReportName() {
        return reportName;
    }

    /* Report_Name */
    public void setReportName(String reportName) {
        this.reportName = reportName;
    }

    /* BarCol_FK */
    public int getBarcolFk() {
        return barcolFk;
    }

    /* BarCol_FK */
    public void setBarcolFk(int barcolFk) {
        this.barcolFk = barcolFk;
    }

    /* SeriesCol_FK */
    public int getSeriescolFk() {
        return seriescolFk;
    }

    /* SeriesCol_FK */
    public void setSeriescolFk(int seriescolFk) {
        this.seriescolFk = seriescolFk;
    }

    /* BarChart_Name */
    public String getBarchartName() {
        return barchartName;
    }

    /* BarChart_Name */
    public void setBarchartName(String barchartName) {
        this.barchartName = barchartName;
    }

    /* PieChart_Name */
    public String getPiechartName() {
        return piechartName;
    }

    /* PieChart_Name */
    public void setPiechartName(String piechartName) {
        this.piechartName = piechartName;
    }

    /* Profile_FK */
    public int getProfileFk() {
        return profileFk;
    }

    /* Profile_FK */
    public void setProfileFk(int profileFk) {
        this.profileFk = profileFk;
    }
  

	public Set<Columns> getColumnSet() {
		return columnSet;
	}

	public void setColumnSet(Set<Columns> columnSet) {
		this.columnSet = columnSet;
	}
}