/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Wed May 05 11:29:43 GMT+05:30 2010
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.scrum.pojo;

/*
 * For Table reports_columns
 */
public class ReportsColumns implements java.io.Serializable, Cloneable {

    /* Report_Columns_ID, PK */
    protected int reportColumnsId;

    /* Report_FK */
    protected int reportFk;

    /* Column_FK */
    protected int columnFk;
 
    /* Report_Columns_ID, PK */
    public int getReportColumnsId() {
        return reportColumnsId;
    }

    /* Report_Columns_ID, PK */
    public void setReportColumnsId(int reportColumnsId) {
        this.reportColumnsId = reportColumnsId;
    }

    /* Report_FK */
    public int getReportFk() {
        return reportFk;
    }

    /* Report_FK */
    public void setReportFk(int reportFk) {
        this.reportFk = reportFk;
    }

    /* Column_FK */
    public int getColumnFk() {
        return columnFk;
    }

    /* Column_FK */
    public void setColumnFk(int columnFk) {
        this.columnFk = columnFk;
    }

 
}