/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Wed May 05 11:29:43 GMT+05:30 2010
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.scrum.pojo;

/*
 * For Table sprintstories
 */
public class Sprintstories implements java.io.Serializable, Cloneable {

    /* sprintstory_ID, PK */
    protected int sprintstoryId;

    /* Sprint_FK */
    protected int sprintFk;

    /* Story_FK */
    protected int storyFk;
 

    /* sprintstory_ID, PK */
    public int getSprintstoryId() {
        return sprintstoryId;
    }

    /* sprintstory_ID, PK */
    public void setSprintstoryId(int sprintstoryId) {
        this.sprintstoryId = sprintstoryId;
    }

    /* Sprint_FK */
    public int getSprintFk() {
        return sprintFk;
    }

    /* Sprint_FK */
    public void setSprintFk(int sprintFk) {
        this.sprintFk = sprintFk;
    }

    /* Story_FK */
    public int getStoryFk() {
        return storyFk;
    }

    /* Story_FK */
    public void setStoryFk(int storyFk) {
        this.storyFk = storyFk;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Sprintstories))
            return false;

        Sprintstories bean = (Sprintstories) obj;

        if (this.sprintstoryId != bean.sprintstoryId)
            return false;

        if (this.sprintFk != bean.sprintFk)
            return false;

        if (this.storyFk != bean.storyFk)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Sprintstories bean = new Sprintstories();
        bean.sprintstoryId = this.sprintstoryId;
        bean.sprintFk = this.sprintFk;
        bean.storyFk = this.storyFk;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("sprintstoryId").append(" = ").append(sprintstoryId).append("]").append(sep);
        sb.append("[").append("sprintFk").append(" = ").append(sprintFk).append("]").append(sep);
        sb.append("[").append("storyFk").append(" = ").append(storyFk).append("]").append(sep);
        return sb.toString();
    }
}