/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Wed May 05 11:29:43 GMT+05:30 2010
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.scrum.pojo;

import java.util.Set;

/*
 * For Table sprints
 */
public class Sprints implements java.io.Serializable, Cloneable {

    /* Sprint_ID, PK */
    protected int sprintId;

    /* Sprint_label */
    protected String sprintLabel;

    /* Sprint_Status_FK */
    protected int sprintStatusFk;
    protected Set<Stories> storySet;
    /* Team_FK */
    protected int teamFk;

    /* Team_FK */
    protected int versionFk;

    /* Product_FK */
    protected int productFk;

    /* s_date_creation */
    protected java.util.Date sDateCreation;

    /* s_date_end */
    protected java.util.Date sDateEnd;

    /* s_date_preparation */
    protected java.util.Date sDatePreparation;

    /* s_date_demo */
    protected java.util.Date sDateDemo;

    /* preparation_Comments */
    protected byte[] preparationComments;

    /* demo_Comments */
    protected byte[] demoComments;
 

    /* Sprint_ID, PK */
    public int getSprintId() {
        return sprintId;
    }

    /* Sprint_ID, PK */
    public void setSprintId(int sprintId) {
        this.sprintId = sprintId;
    }

    /* Sprint_label */
    public String getSprintLabel() {
        return sprintLabel;
    }

    /* Sprint_label */
    public void setSprintLabel(String sprintLabel) {
        this.sprintLabel = sprintLabel;
    }

    /* Sprint_Status_FK */
    public int getSprintStatusFk() {
        return sprintStatusFk;
    }

    /* Sprint_Status_FK */
    public void setSprintStatusFk(int sprintStatusFk) {
        this.sprintStatusFk = sprintStatusFk;
    }

    /* Team_FK */
    public int getTeamFk() {
        return teamFk;
    }

    /* Team_FK */
    public void setTeamFk(int teamFk) {
        this.teamFk = teamFk;
    }

    /* Product_FK */
    public int getProductFk() {
        return productFk;
    }

    /* Product_FK */
    public void setProductFk(int productFk) {
        this.productFk = productFk;
    }

    /* s_date_creation */
    public java.util.Date getSDateCreation() {
        return sDateCreation;
    }

    /* s_date_creation */
    public void setSDateCreation(java.util.Date sDateCreation) {
        this.sDateCreation = sDateCreation;
    }

    /* s_date_end */
    public java.util.Date getSDateEnd() {
        return sDateEnd;
    }

    /* s_date_end */
    public void setSDateEnd(java.util.Date sDateEnd) {
        this.sDateEnd = sDateEnd;
    }

    /* s_date_preparation */
    public java.util.Date getSDatePreparation() {
        return sDatePreparation;
    }

    /* s_date_preparation */
    public void setSDatePreparation(java.util.Date sDatePreparation) {
        this.sDatePreparation = sDatePreparation;
    }

    /* s_date_demo */
    public java.util.Date getSDateDemo() {
        return sDateDemo;
    }

    /* s_date_demo */
    public void setSDateDemo(java.util.Date sDateDemo) {
        this.sDateDemo = sDateDemo;
    }

    /* preparation_Comments */
    public byte[] getPreparationComments() {
        return preparationComments;
    }

    /* preparation_Comments */
    public void setPreparationComments(byte[] preparationComments) {
        this.preparationComments = preparationComments;
    }

    /* demo_Comments */
    public byte[] getDemoComments() {
        return demoComments;
    }

    /* demo_Comments */
    public void setDemoComments(byte[] demoComments) {
        this.demoComments = demoComments;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Sprints))
            return false;

        Sprints bean = (Sprints) obj;

        if (this.sprintId != bean.sprintId)
            return false;

        if (this.sprintLabel == null) {
            if (bean.sprintLabel != null)
                return false;
        }
        else if (!this.sprintLabel.equals(bean.sprintLabel)) 
            return false;

        if (this.sprintStatusFk != bean.sprintStatusFk)
            return false;

        if (this.teamFk != bean.teamFk)
            return false;

        if (this.productFk != bean.productFk)
            return false;

        if (this.sDateCreation == null) {
            if (bean.sDateCreation != null)
                return false;
        }
        else if (!this.sDateCreation.equals(bean.sDateCreation)) 
            return false;

        if (this.sDateEnd == null) {
            if (bean.sDateEnd != null)
                return false;
        }
        else if (!this.sDateEnd.equals(bean.sDateEnd)) 
            return false;

        if (this.sDatePreparation == null) {
            if (bean.sDatePreparation != null)
                return false;
        }
        else if (!this.sDatePreparation.equals(bean.sDatePreparation)) 
            return false;

        if (this.sDateDemo == null) {
            if (bean.sDateDemo != null)
                return false;
        }
        else if (!this.sDateDemo.equals(bean.sDateDemo)) 
            return false;

        if (this.preparationComments == null) {
            if (bean.preparationComments != null)
                return false;
        }else {
            if (bean.preparationComments == null)
                return false;
            else {
                if (preparationComments.length != bean.preparationComments.length)
                    return false;
                for (int i=0;i<bean.preparationComments.length;i++) {
                    if (this.preparationComments[i] != bean.preparationComments[i])
                        return false;
                }
            }
        }

        if (this.demoComments == null) {
            if (bean.demoComments != null)
                return false;
        }else {
            if (bean.demoComments == null)
                return false;
            else {
                if (demoComments.length != bean.demoComments.length)
                    return false;
                for (int i=0;i<bean.demoComments.length;i++) {
                    if (this.demoComments[i] != bean.demoComments[i])
                        return false;
                }
            }
        }

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Sprints bean = new Sprints();
        bean.sprintId = this.sprintId;
        bean.sprintLabel = this.sprintLabel;
        bean.sprintStatusFk = this.sprintStatusFk;
        bean.teamFk = this.teamFk;
        bean.productFk = this.productFk;
        if (this.sDateCreation != null)
            bean.sDateCreation = (java.util.Date) this.sDateCreation.clone();
        if (this.sDateEnd != null)
            bean.sDateEnd = (java.util.Date) this.sDateEnd.clone();
        if (this.sDatePreparation != null)
            bean.sDatePreparation = (java.util.Date) this.sDatePreparation.clone();
        if (this.sDateDemo != null)
            bean.sDateDemo = (java.util.Date) this.sDateDemo.clone();
        int preparationCommentsLength = -1;
        if (this.preparationComments != null)
            preparationCommentsLength = this.preparationComments.length;
        if (preparationCommentsLength > 0)
        {
            byte[] preparationCommentsArray = new byte[preparationCommentsLength];
            bean.preparationComments = preparationCommentsArray;
            System.arraycopy(this.preparationComments, 0, preparationCommentsArray, 0, preparationCommentsLength);
        }
        int demoCommentsLength = -1;
        if (this.demoComments != null)
            demoCommentsLength = this.demoComments.length;
        if (demoCommentsLength > 0)
        {
            byte[] demoCommentsArray = new byte[demoCommentsLength];
            bean.demoComments = demoCommentsArray;
            System.arraycopy(this.demoComments, 0, demoCommentsArray, 0, demoCommentsLength);
        }
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("sprintId").append(" = ").append(sprintId).append("]").append(sep);
        sb.append("[").append("sprintLabel").append(" = ").append(sprintLabel).append("]").append(sep);
        sb.append("[").append("sprintStatusFk").append(" = ").append(sprintStatusFk).append("]").append(sep);
        sb.append("[").append("teamFk").append(" = ").append(teamFk).append("]").append(sep);
        sb.append("[").append("productFk").append(" = ").append(productFk).append("]").append(sep);
        sb.append("[").append("sDateCreation").append(" = ").append(sDateCreation).append("]").append(sep);
        sb.append("[").append("sDateEnd").append(" = ").append(sDateEnd).append("]").append(sep);
        sb.append("[").append("sDatePreparation").append(" = ").append(sDatePreparation).append("]").append(sep);
        sb.append("[").append("sDateDemo").append(" = ").append(sDateDemo).append("]").append(sep);
        sb.append("[").append("preparationComments").append(" = ").append(preparationComments).append("]").append(sep);
        sb.append("[").append("demoComments").append(" = ").append(demoComments).append("]").append(sep);
        return sb.toString();
    }

	public int getVersionFk() {
		return versionFk;
	}

	public void setVersionFk(int versionFk) {
		this.versionFk = versionFk;
	}

	public Set<Stories> getStorySet() {
		return storySet;
	}

	public void setStorySet(Set<Stories> storySet) {
		this.storySet = storySet;
	}
}