/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Wed May 05 11:29:43 GMT+05:30 2010
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.scrum.pojo;

/*
 * For Table tickets
 */
public class Tickets implements java.io.Serializable, Cloneable {

    /* Ticket_ID, PK */
    protected int ticketId;

    /* Person_FK */
    protected int personFk;

    /* Task_FK */
    protected int taskFk;

    /* Ticket_Date */
    protected java.util.Date ticketDate;

    /* Ticket_TimeSpent */
    protected int ticketTimespent;

    /* Ticket_Comments */
    protected String ticketComments;

    /* Ticket_Technical */
    protected byte[] ticketTechnical;
 

    /* Ticket_ID, PK */
    public int getTicketId() {
        return ticketId;
    }

    /* Ticket_ID, PK */
    public void setTicketId(int ticketId) {
        this.ticketId = ticketId;
    }

    /* Person_FK */
    public int getPersonFk() {
        return personFk;
    }

    /* Person_FK */
    public void setPersonFk(int personFk) {
        this.personFk = personFk;
    }

    /* Task_FK */
    public int getTaskFk() {
        return taskFk;
    }

    /* Task_FK */
    public void setTaskFk(int taskFk) {
        this.taskFk = taskFk;
    }

    /* Ticket_Date */
    public java.util.Date getTicketDate() {
        return ticketDate;
    }

    /* Ticket_Date */
    public void setTicketDate(java.util.Date ticketDate) {
        this.ticketDate = ticketDate;
    }

    /* Ticket_TimeSpent */
    public int getTicketTimespent() {
        return ticketTimespent;
    }

    /* Ticket_TimeSpent */
    public void setTicketTimespent(int ticketTimespent) {
        this.ticketTimespent = ticketTimespent;
    }

    /* Ticket_Comments */
    public String getTicketComments() {
        return ticketComments;
    }

    /* Ticket_Comments */
    public void setTicketComments(String ticketComments) {
        this.ticketComments = ticketComments;
    }

    /* Ticket_Technical */
    public byte[] getTicketTechnical() {
        return ticketTechnical;
    }

    /* Ticket_Technical */
    public void setTicketTechnical(byte[] ticketTechnical) {
        this.ticketTechnical = ticketTechnical;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Tickets))
            return false;

        Tickets bean = (Tickets) obj;

        if (this.ticketId != bean.ticketId)
            return false;

        if (this.personFk != bean.personFk)
            return false;

        if (this.taskFk != bean.taskFk)
            return false;

        if (this.ticketDate == null) {
            if (bean.ticketDate != null)
                return false;
        }
        else if (!this.ticketDate.equals(bean.ticketDate)) 
            return false;

        if (this.ticketTimespent != bean.ticketTimespent)
            return false;

        if (this.ticketComments == null) {
            if (bean.ticketComments != null)
                return false;
        }
        else if (!this.ticketComments.equals(bean.ticketComments)) 
            return false;

        if (this.ticketTechnical == null) {
            if (bean.ticketTechnical != null)
                return false;
        }else {
            if (bean.ticketTechnical == null)
                return false;
            else {
                if (ticketTechnical.length != bean.ticketTechnical.length)
                    return false;
                for (int i=0;i<bean.ticketTechnical.length;i++) {
                    if (this.ticketTechnical[i] != bean.ticketTechnical[i])
                        return false;
                }
            }
        }

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Tickets bean = new Tickets();
        bean.ticketId = this.ticketId;
        bean.personFk = this.personFk;
        bean.taskFk = this.taskFk;
        if (this.ticketDate != null)
            bean.ticketDate = (java.util.Date) this.ticketDate.clone();
        bean.ticketTimespent = this.ticketTimespent;
        bean.ticketComments = this.ticketComments;
        int ticketTechnicalLength = -1;
        if (this.ticketTechnical != null)
            ticketTechnicalLength = this.ticketTechnical.length;
        if (ticketTechnicalLength > 0)
        {
            byte[] ticketTechnicalArray = new byte[ticketTechnicalLength];
            bean.ticketTechnical = ticketTechnicalArray;
            System.arraycopy(this.ticketTechnical, 0, ticketTechnicalArray, 0, ticketTechnicalLength);
        }
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("ticketId").append(" = ").append(ticketId).append("]").append(sep);
        sb.append("[").append("personFk").append(" = ").append(personFk).append("]").append(sep);
        sb.append("[").append("taskFk").append(" = ").append(taskFk).append("]").append(sep);
        sb.append("[").append("ticketDate").append(" = ").append(ticketDate).append("]").append(sep);
        sb.append("[").append("ticketTimespent").append(" = ").append(ticketTimespent).append("]").append(sep);
        sb.append("[").append("ticketComments").append(" = ").append(ticketComments).append("]").append(sep);
        sb.append("[").append("ticketTechnical").append(" = ").append(ticketTechnical).append("]").append(sep);
        return sb.toString();
    }
}