/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Wed May 05 11:29:43 GMT+05:30 2010
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.scrum.pojo;

/*
 * For Table events
 */
public class Events implements java.io.Serializable, Cloneable {

    /* event_ID, PK */
    protected int eventId;

    /* event_date */
    protected java.util.Date eventDate;

    /* event_status_FK */
    protected int eventStatusFk;

    /* person_FK */
    protected int personFk;

    /* task_FK */
    protected int taskFk;

    /* product_FK */
    protected int productFk;

    /* event_label */
    protected String eventLabel;

    /* story_FK */
    protected int storyFk;

    /* sprint_FK */
    protected int sprintFk;

    /* ticket_FK */
    protected int ticketFk; 
    /* event_ID, PK */
    public int getEventId() {
        return eventId;
    }

    /* event_ID, PK */
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }

    /* event_date */
    public java.util.Date getEventDate() {
        return eventDate;
    }

    /* event_date */
    public void setEventDate(java.util.Date eventDate) {
        this.eventDate = eventDate;
    }

    /* event_status_FK */
    public int getEventStatusFk() {
        return eventStatusFk;
    }

    /* event_status_FK */
    public void setEventStatusFk(int eventStatusFk) {
        this.eventStatusFk = eventStatusFk;
    }

    /* person_FK */
    public int getPersonFk() {
        return personFk;
    }

    /* person_FK */
    public void setPersonFk(int personFk) {
        this.personFk = personFk;
    }

    /* task_FK */
    public int getTaskFk() {
        return taskFk;
    }

    /* task_FK */
    public void setTaskFk(int taskFk) {
        this.taskFk = taskFk;
    }

    /* product_FK */
    public int getProductFk() {
        return productFk;
    }

    /* product_FK */
    public void setProductFk(int productFk) {
        this.productFk = productFk;
    }

    /* event_label */
    public String getEventLabel() {
        return eventLabel;
    }

    /* event_label */
    public void setEventLabel(String eventLabel) {
        this.eventLabel = eventLabel;
    }

    /* story_FK */
    public int getStoryFk() {
        return storyFk;
    }

    /* story_FK */
    public void setStoryFk(int storyFk) {
        this.storyFk = storyFk;
    }

    /* sprint_FK */
    public int getSprintFk() {
        return sprintFk;
    }

    /* sprint_FK */
    public void setSprintFk(int sprintFk) {
        this.sprintFk = sprintFk;
    }

    /* ticket_FK */
    public int getTicketFk() {
        return ticketFk;
    }

    /* ticket_FK */
    public void setTicketFk(int ticketFk) {
        this.ticketFk = ticketFk;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Events))
            return false;

        Events bean = (Events) obj;

        if (this.eventId != bean.eventId)
            return false;

        if (this.eventDate == null) {
            if (bean.eventDate != null)
                return false;
        }
        else if (!this.eventDate.equals(bean.eventDate)) 
            return false;

        if (this.eventStatusFk != bean.eventStatusFk)
            return false;

        if (this.personFk != bean.personFk)
            return false;

        if (this.taskFk != bean.taskFk)
            return false;

        if (this.productFk != bean.productFk)
            return false;

        if (this.eventLabel == null) {
            if (bean.eventLabel != null)
                return false;
        }
        else if (!this.eventLabel.equals(bean.eventLabel)) 
            return false;

        if (this.storyFk != bean.storyFk)
            return false;

        if (this.sprintFk != bean.sprintFk)
            return false;

        if (this.ticketFk != bean.ticketFk)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Events bean = new Events();
        bean.eventId = this.eventId;
        if (this.eventDate != null)
            bean.eventDate = (java.util.Date) this.eventDate.clone();
        bean.eventStatusFk = this.eventStatusFk;
        bean.personFk = this.personFk;
        bean.taskFk = this.taskFk;
        bean.productFk = this.productFk;
        bean.eventLabel = this.eventLabel;
        bean.storyFk = this.storyFk;
        bean.sprintFk = this.sprintFk;
        bean.ticketFk = this.ticketFk;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("eventId").append(" = ").append(eventId).append("]").append(sep);
        sb.append("[").append("eventDate").append(" = ").append(eventDate).append("]").append(sep);
        sb.append("[").append("eventStatusFk").append(" = ").append(eventStatusFk).append("]").append(sep);
        sb.append("[").append("personFk").append(" = ").append(personFk).append("]").append(sep);
        sb.append("[").append("taskFk").append(" = ").append(taskFk).append("]").append(sep);
        sb.append("[").append("productFk").append(" = ").append(productFk).append("]").append(sep);
        sb.append("[").append("eventLabel").append(" = ").append(eventLabel).append("]").append(sep);
        sb.append("[").append("storyFk").append(" = ").append(storyFk).append("]").append(sep);
        sb.append("[").append("sprintFk").append(" = ").append(sprintFk).append("]").append(sep);
        sb.append("[").append("ticketFk").append(" = ").append(ticketFk).append("]").append(sep);
        return sb.toString();
    }
}