/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Wed May 05 11:29:43 GMT+05:30 2010
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.scrum.pojo;

/*
 * For Table status
 */
public class Status implements java.io.Serializable, Cloneable {

    /* status_ID, PK */
    protected int statusId;

    /* type */
    protected String type;

    /* status_label */
    protected String statusLabel;
 
    /* status_ID, PK */
    public int getStatusId() {
        return statusId;
    }

    /* status_ID, PK */
    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }

    /* type */
    public String getType() {
        return type;
    }

    /* type */
    public void setType(String type) {
        this.type = type;
    }

    /* status_label */
    public String getStatusLabel() {
        return statusLabel;
    }

    /* status_label */
    public void setStatusLabel(String statusLabel) {
        this.statusLabel = statusLabel;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Status))
            return false;

        Status bean = (Status) obj;

        if (this.statusId != bean.statusId)
            return false;

        if (this.type == null) {
            if (bean.type != null)
                return false;
        }
        else if (!this.type.equals(bean.type)) 
            return false;

        if (this.statusLabel == null) {
            if (bean.statusLabel != null)
                return false;
        }
        else if (!this.statusLabel.equals(bean.statusLabel)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Status bean = new Status();
        bean.statusId = this.statusId;
        bean.type = this.type;
        bean.statusLabel = this.statusLabel;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("statusId").append(" = ").append(statusId).append("]").append(sep);
        sb.append("[").append("type").append(" = ").append(type).append("]").append(sep);
        sb.append("[").append("statusLabel").append(" = ").append(statusLabel).append("]").append(sep);
        return sb.toString();
    }
}