/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Wed May 05 11:29:43 GMT+05:30 2010
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.scrum.pojo;

/*
 * For Table storythemes
 */
public class Storythemes implements java.io.Serializable, Cloneable {

    /* story_theme_id, PK */
    protected int storyThemeId;

    /* story_FK */
    protected int storyFk;

    /* theme_FK */
    protected int themeFk;
 
    /* story_theme_id, PK */
    public int getStoryThemeId() {
        return storyThemeId;
    }

    /* story_theme_id, PK */
    public void setStoryThemeId(int storyThemeId) {
        this.storyThemeId = storyThemeId;
    }

    /* story_FK */
    public int getStoryFk() {
        return storyFk;
    }

    /* story_FK */
    public void setStoryFk(int storyFk) {
        this.storyFk = storyFk;
    }

    /* theme_FK */
    public int getThemeFk() {
        return themeFk;
    }

    /* theme_FK */
    public void setThemeFk(int themeFk) {
        this.themeFk = themeFk;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Storythemes))
            return false;

        Storythemes bean = (Storythemes) obj;

        if (this.storyThemeId != bean.storyThemeId)
            return false;

        if (this.storyFk != bean.storyFk)
            return false;

        if (this.themeFk != bean.themeFk)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Storythemes bean = new Storythemes();
        bean.storyThemeId = this.storyThemeId;
        bean.storyFk = this.storyFk;
        bean.themeFk = this.themeFk;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("storyThemeId").append(" = ").append(storyThemeId).append("]").append(sep);
        sb.append("[").append("storyFk").append(" = ").append(storyFk).append("]").append(sep);
        sb.append("[").append("themeFk").append(" = ").append(themeFk).append("]").append(sep);
        return sb.toString();
    }
}