/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Wed May 05 11:29:43 GMT+05:30 2010
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.scrum.pojo;

import java.util.Set;

/*
 * For Table stories
 */
public class Stories implements java.io.Serializable, Cloneable {

    /* story_ID, PK */
    protected int storyId;

    /* Product_FK */
    protected int productFk;
    protected Set<Tasks> taskSet;
    protected Set<Themes> themeSet;
    public Set<Themes> getThemeSet() {
		return themeSet;
	}

	public void setThemeSet(Set<Themes> themeSet) {
		this.themeSet = themeSet;
	}

	/* As_label */
    protected int asLabel;

    /* I_Want_To_label */
    protected String iWantToLabel;

    /* So_That_I_Can_label */
    protected String soThatICanLabel;

    /* Story_status_FK */
    protected int storyStatusFk;

    /* version_FK */
    protected int versionFk;

    /* visible */
    protected boolean visible;

    /* Story_comments */
    protected byte[] storyComments;

    /* StoryPoints */
    protected int storypoints;

    /* Priority */
    protected int priority;

    /* Effort */
    protected int effort;

    /* story_ID, PK */
    public int getStoryId() {
        return storyId;
    }

    /* story_ID, PK */
    public void setStoryId(int storyId) {
        this.storyId = storyId;
    }

    /* Product_FK */
    public int getProductFk() {
        return productFk;
    }

    /* Product_FK */
    public void setProductFk(int productFk) {
        this.productFk = productFk;
    }

    /* As_label */
    public int getAsLabel() {
        return asLabel;
    }

    /* As_label */
    public void setAsLabel(int asLabel) {
        this.asLabel = asLabel;
    }

    /* I_Want_To_label */
    public String getIWantToLabel() {
        return iWantToLabel;
    }

    /* I_Want_To_label */
    public void setIWantToLabel(String iWantToLabel) {
        this.iWantToLabel = iWantToLabel;
    }

    /* So_That_I_Can_label */
    public String getSoThatICanLabel() {
        return soThatICanLabel;
    }

    /* So_That_I_Can_label */
    public void setSoThatICanLabel(String soThatICanLabel) {
        this.soThatICanLabel = soThatICanLabel;
    }

    /* Story_status_FK */
    public int getStoryStatusFk() {
        return storyStatusFk;
    }

    /* Story_status_FK */
    public void setStoryStatusFk(int storyStatusFk) {
        this.storyStatusFk = storyStatusFk;
    }

    /* version_FK */
    public int getVersionFk() {
        return versionFk;
    }

    /* version_FK */
    public void setVersionFk(int versionFk) {
        this.versionFk = versionFk;
    }

    /* visible */
    public boolean getVisible() {
        return visible;
    }

    /* visible */
    public void setVisible(boolean visible) {
        this.visible = visible;
    }

    /* Story_comments */
    public byte[] getStoryComments() {
        return storyComments;
    }

    /* Story_comments */
    public void setStoryComments(byte[] storyComments) {
        this.storyComments = storyComments;
    }

    /* StoryPoints */
    public int getStorypoints() {
        return storypoints;
    }

    /* StoryPoints */
    public void setStorypoints(int storypoints) {
        this.storypoints = storypoints;
    }

    /* Priority */
    public int getPriority() {
        return priority;
    }

    /* Priority */
    public void setPriority(int priority) {
        this.priority = priority;
    }

    /* Effort */
    public int getEffort() {
        return effort;
    }

    /* Effort */
    public void setEffort(int effort) {
        this.effort = effort;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Stories))
            return false;

        Stories bean = (Stories) obj;

        if (this.storyId != bean.storyId)
            return false;

        if (this.productFk != bean.productFk)
            return false;

        if (this.asLabel != bean.asLabel)
            return false;

        if (this.iWantToLabel == null) {
            if (bean.iWantToLabel != null)
                return false;
        }
        else if (!this.iWantToLabel.equals(bean.iWantToLabel)) 
            return false;

        if (this.soThatICanLabel == null) {
            if (bean.soThatICanLabel != null)
                return false;
        }
        else if (!this.soThatICanLabel.equals(bean.soThatICanLabel)) 
            return false;

        if (this.storyStatusFk != bean.storyStatusFk)
            return false;

        if (this.versionFk != bean.versionFk)
            return false;

        if (this.visible != bean.visible)
            return false;

        if (this.storyComments == null) {
            if (bean.storyComments != null)
                return false;
        }else {
            if (bean.storyComments == null)
                return false;
            else {
                if (storyComments.length != bean.storyComments.length)
                    return false;
                for (int i=0;i<bean.storyComments.length;i++) {
                    if (this.storyComments[i] != bean.storyComments[i])
                        return false;
                }
            }
        }

        if (this.storypoints != bean.storypoints)
            return false;

        if (this.priority != bean.priority)
            return false;

        if (this.effort != bean.effort)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Stories bean = new Stories();
        bean.storyId = this.storyId;
        bean.productFk = this.productFk;
        bean.asLabel = this.asLabel;
        bean.iWantToLabel = this.iWantToLabel;
        bean.soThatICanLabel = this.soThatICanLabel;
        bean.storyStatusFk = this.storyStatusFk;
        bean.versionFk = this.versionFk;
        bean.visible = this.visible;
        int storyCommentsLength = -1;
        if (this.storyComments != null)
            storyCommentsLength = this.storyComments.length;
        if (storyCommentsLength > 0)
        {
            byte[] storyCommentsArray = new byte[storyCommentsLength];
            bean.storyComments = storyCommentsArray;
            System.arraycopy(this.storyComments, 0, storyCommentsArray, 0, storyCommentsLength);
        }
        bean.storypoints = this.storypoints;
        bean.priority = this.priority;
        bean.effort = this.effort;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("storyId").append(" = ").append(storyId).append("]").append(sep);
        sb.append("[").append("productFk").append(" = ").append(productFk).append("]").append(sep);
        sb.append("[").append("asLabel").append(" = ").append(asLabel).append("]").append(sep);
        sb.append("[").append("iWantToLabel").append(" = ").append(iWantToLabel).append("]").append(sep);
        sb.append("[").append("soThatICanLabel").append(" = ").append(soThatICanLabel).append("]").append(sep);
        sb.append("[").append("storyStatusFk").append(" = ").append(storyStatusFk).append("]").append(sep);
        sb.append("[").append("versionFk").append(" = ").append(versionFk).append("]").append(sep);
        sb.append("[").append("visible").append(" = ").append(visible).append("]").append(sep);
        sb.append("[").append("storyComments").append(" = ").append(storyComments).append("]").append(sep);
        sb.append("[").append("storypoints").append(" = ").append(storypoints).append("]").append(sep);
        sb.append("[").append("priority").append(" = ").append(priority).append("]").append(sep);
        sb.append("[").append("effort").append(" = ").append(effort).append("]").append(sep);
        return sb.toString();
    }

	public Set<Tasks> getTaskSet() {
		return taskSet;
	}

	public void setTaskSet(Set<Tasks> taskSet) {
		this.taskSet = taskSet;
	}
}