/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Wed May 05 11:29:43 GMT+05:30 2010
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.scrum.pojo;

/*
 * For Table tasks
 */
public class Tasks implements java.io.Serializable, Cloneable {

    /* task_ID, PK */
    protected int taskId;

    /* story_FK */
    protected int storyFk;

    /* task_comment */
    protected byte[] taskComment;

    /* task_status_FK */
    protected int taskStatusFk;

    /* task_type */
    protected int taskType;

    /* t_date_creation */
    protected java.util.Date tDateCreation;

    /* t_date_inprogress */
    protected java.util.Date tDateInprogress;

    /* t_date_validation */
    protected java.util.Date tDateValidation;

    /* t_date_done */
    protected java.util.Date tDateDone;

    /* onair_time */
    protected int onairTime;

    /* estimated_time */
    protected int estimatedTime;

    /* done_time */
    protected int doneTime;

    /* person_FK */
    protected int personFk;

    /* visible */
    protected int visible;
 

    /* task_ID, PK */
    public int getTaskId() {
        return taskId;
    }

    /* task_ID, PK */
    public void setTaskId(int taskId) {
        this.taskId = taskId;
    }

    /* story_FK */
    public int getStoryFk() {
        return storyFk;
    }

    /* story_FK */
    public void setStoryFk(int storyFk) {
        this.storyFk = storyFk;
    }

    /* task_comment */
    public byte[] getTaskComment() {
        return taskComment;
    }

    /* task_comment */
    public void setTaskComment(byte[] taskComment) {
        this.taskComment = taskComment;
    }

    /* task_status_FK */
    public int getTaskStatusFk() {
        return taskStatusFk;
    }

    /* task_status_FK */
    public void setTaskStatusFk(int taskStatusFk) {
        this.taskStatusFk = taskStatusFk;
    }

    /* task_type */
    public int getTaskType() {
        return taskType;
    }

    /* task_type */
    public void setTaskType(int taskType) {
        this.taskType = taskType;
    }

    /* t_date_creation */
    public java.util.Date getTDateCreation() {
        return tDateCreation;
    }

    /* t_date_creation */
    public void setTDateCreation(java.util.Date tDateCreation) {
        this.tDateCreation = tDateCreation;
    }

    /* t_date_inprogress */
    public java.util.Date getTDateInprogress() {
        return tDateInprogress;
    }

    /* t_date_inprogress */
    public void setTDateInprogress(java.util.Date tDateInprogress) {
        this.tDateInprogress = tDateInprogress;
    }

    /* t_date_validation */
    public java.util.Date getTDateValidation() {
        return tDateValidation;
    }

    /* t_date_validation */
    public void setTDateValidation(java.util.Date tDateValidation) {
        this.tDateValidation = tDateValidation;
    }

    /* t_date_done */
    public java.util.Date getTDateDone() {
        return tDateDone;
    }

    /* t_date_done */
    public void setTDateDone(java.util.Date tDateDone) {
        this.tDateDone = tDateDone;
    }

    /* onair_time */
    public int getOnairTime() {
        return onairTime;
    }

    /* onair_time */
    public void setOnairTime(int onairTime) {
        this.onairTime = onairTime;
    }

    /* estimated_time */
    public int getEstimatedTime() {
        return estimatedTime;
    }

    /* estimated_time */
    public void setEstimatedTime(int estimatedTime) {
        this.estimatedTime = estimatedTime;
    }

    /* done_time */
    public int getDoneTime() {
        return doneTime;
    }

    /* done_time */
    public void setDoneTime(int doneTime) {
        this.doneTime = doneTime;
    }

    /* person_FK */
    public int getPersonFk() {
        return personFk;
    }

    /* person_FK */
    public void setPersonFk(int personFk) {
        this.personFk = personFk;
    }

    /* visible */
    public int getVisible() {
        return visible;
    }

    /* visible */
    public void setVisible(int visible) {
        this.visible = visible;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Tasks))
            return false;

        Tasks bean = (Tasks) obj;

        if (this.taskId != bean.taskId)
            return false;

        if (this.storyFk != bean.storyFk)
            return false;

        if (this.taskComment == null) {
            if (bean.taskComment != null)
                return false;
        }else {
            if (bean.taskComment == null)
                return false;
            else {
                if (taskComment.length != bean.taskComment.length)
                    return false;
                for (int i=0;i<bean.taskComment.length;i++) {
                    if (this.taskComment[i] != bean.taskComment[i])
                        return false;
                }
            }
        }

        if (this.taskStatusFk != bean.taskStatusFk)
            return false;

        if (this.taskType != bean.taskType)
            return false;

        if (this.tDateCreation == null) {
            if (bean.tDateCreation != null)
                return false;
        }
        else if (!this.tDateCreation.equals(bean.tDateCreation)) 
            return false;

        if (this.tDateInprogress == null) {
            if (bean.tDateInprogress != null)
                return false;
        }
        else if (!this.tDateInprogress.equals(bean.tDateInprogress)) 
            return false;

        if (this.tDateValidation == null) {
            if (bean.tDateValidation != null)
                return false;
        }
        else if (!this.tDateValidation.equals(bean.tDateValidation)) 
            return false;

        if (this.tDateDone == null) {
            if (bean.tDateDone != null)
                return false;
        }
        else if (!this.tDateDone.equals(bean.tDateDone)) 
            return false;

        if (this.onairTime != bean.onairTime)
            return false;

        if (this.estimatedTime != bean.estimatedTime)
            return false;

        if (this.doneTime != bean.doneTime)
            return false;

        if (this.personFk != bean.personFk)
            return false;

        if (this.visible != bean.visible)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Tasks bean = new Tasks();
        bean.taskId = this.taskId;
        bean.storyFk = this.storyFk;
        int taskCommentLength = -1;
        if (this.taskComment != null)
            taskCommentLength = this.taskComment.length;
        if (taskCommentLength > 0)
        {
            byte[] taskCommentArray = new byte[taskCommentLength];
            bean.taskComment = taskCommentArray;
            System.arraycopy(this.taskComment, 0, taskCommentArray, 0, taskCommentLength);
        }
        bean.taskStatusFk = this.taskStatusFk;
        bean.taskType = this.taskType;
        if (this.tDateCreation != null)
            bean.tDateCreation = (java.util.Date) this.tDateCreation.clone();
        if (this.tDateInprogress != null)
            bean.tDateInprogress = (java.util.Date) this.tDateInprogress.clone();
        if (this.tDateValidation != null)
            bean.tDateValidation = (java.util.Date) this.tDateValidation.clone();
        if (this.tDateDone != null)
            bean.tDateDone = (java.util.Date) this.tDateDone.clone();
        bean.onairTime = this.onairTime;
        bean.estimatedTime = this.estimatedTime;
        bean.doneTime = this.doneTime;
        bean.personFk = this.personFk;
        bean.visible = this.visible;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("taskId").append(" = ").append(taskId).append("]").append(sep);
        sb.append("[").append("storyFk").append(" = ").append(storyFk).append("]").append(sep);
        sb.append("[").append("taskComment").append(" = ").append(taskComment).append("]").append(sep);
        sb.append("[").append("taskStatusFk").append(" = ").append(taskStatusFk).append("]").append(sep);
        sb.append("[").append("taskType").append(" = ").append(taskType).append("]").append(sep);
        sb.append("[").append("tDateCreation").append(" = ").append(tDateCreation).append("]").append(sep);
        sb.append("[").append("tDateInprogress").append(" = ").append(tDateInprogress).append("]").append(sep);
        sb.append("[").append("tDateValidation").append(" = ").append(tDateValidation).append("]").append(sep);
        sb.append("[").append("tDateDone").append(" = ").append(tDateDone).append("]").append(sep);
        sb.append("[").append("onairTime").append(" = ").append(onairTime).append("]").append(sep);
        sb.append("[").append("estimatedTime").append(" = ").append(estimatedTime).append("]").append(sep);
        sb.append("[").append("doneTime").append(" = ").append(doneTime).append("]").append(sep);
        sb.append("[").append("personFk").append(" = ").append(personFk).append("]").append(sep);
        sb.append("[").append("visible").append(" = ").append(visible).append("]").append(sep);
        return sb.toString();
    }
}