/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Wed May 05 11:29:43 GMT+05:30 2010
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.scrum.pojo;

import java.util.Set;

/*
 * For Table teams
 */
public class Teams implements java.io.Serializable, Cloneable {

    /* team_ID, PK */
    protected int teamId;

    /* team_label */
    protected String teamLabel;
 
    protected Set<Teammembers> teamMemberSet; 

	public Set<Teammembers> getTeamMemberSet() {
		return teamMemberSet;
	}

	public void setTeamMemberSet(Set<Teammembers> teamMemberSet) {
		this.teamMemberSet = teamMemberSet;
	}

	/* team_ID, PK */
    public int getTeamId() {
        return teamId;
    }

    /* team_ID, PK */
    public void setTeamId(int teamId) {
        this.teamId = teamId;
    }

    /* team_label */
    public String getTeamLabel() {
        return teamLabel;
    }

    /* team_label */
    public void setTeamLabel(String teamLabel) {
        this.teamLabel = teamLabel;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Teams))
            return false;

        Teams bean = (Teams) obj;

        if (this.teamId != bean.teamId)
            return false;

        if (this.teamLabel == null) {
            if (bean.teamLabel != null)
                return false;
        }
        else if (!this.teamLabel.equals(bean.teamLabel)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Teams bean = new Teams();
        bean.teamId = this.teamId;
        bean.teamLabel = this.teamLabel;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("teamId").append(" = ").append(teamId).append("]").append(sep);
        sb.append("[").append("teamLabel").append(" = ").append(teamLabel).append("]").append(sep);
        return sb.toString();
    }
}